components:
    securitySchemes:
      BasicAuth:
        type: http
        scheme: basic
    schemas:
        Question:
            type: object
            required:
                - id
                - name
                - index
                - selectedAnswer
                - answers
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                index:
                    type: integer
                    format: int32
                selectedAnswer:
                    type: string
                options:
                    type: array
                    items:
                        type: string
info:
    description: "An API to retrieve and update the readiness for a user"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "NHS Talent - User Readiness"
    version: "1.0.0"
openapi: 3.0.1
security: 
  - BasicAuth: []
servers: 
  - url: http://localhost:8080/o/nhs-headless-user-readiness/1.0.0
paths:
    "/user-profile/questionnaire":
        get:
            description: Returns the whole user readiness questionnaire
            operationId: getUserProfileQuestionnairePage
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: "array"
                                items:
                                    $ref: "#/components/schemas/Question"
                        application/xml:
                            schema:
                                type: "array"
                                items:
                                    $ref: "#/components/schemas/Question"
                    description: OK
                403:
                  description: Forbidden
            tags: ["Question"]
    "/user-profile/questionnaire-intro":
        get:
            description: Returns the help information displayed in the first page of the questionnaire
            operationId: getUserProfileQuestionnaireIntro
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: "string"
                        application/xml:
                            schema:
                                type: "string"
                    description: OK
                403:
                  description: Forbidden
            tags: ["Question"]
    "/user-profile/question/{questionId}":
        get:
            description: Returns a single question
            operationId: getUserProfileQuestion
            parameters:
                - in: path
                  name: questionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Question"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Question"
                    description: OK
                403:
                  description: Forbidden
            tags: ["Question"]
        put:
            description: Updates the answer to a single question
            operationId: putUserProfileQuestion
            parameters:
                - in: path
                  name: questionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    text/plain:
                        schema:
                            type: string
            responses:
                200:
                    content:
                        {}
                    description: OK
                403:
                  description: Forbidden
            tags: ["Question"]
        delete:
            description: Deletes the answer for a single question
            operationId: deleteUserProfileQuestion
            parameters:
                - in: path
                  name: questionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        {}
                    description: OK
                403:
                  description: Forbidden
            tags: ["Question"]